apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horusec-api
  name: api
  namespace: horusec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horusec-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horusec-api
    spec:
      containers:
        - env:
            - name: HORUSEC_SWAGGER_HOST
              value: 0.0.0.0
            - name: HORUSEC_BROKER_HOST
              value: rabbitmq.queue
            - name: HORUSEC_BROKER_PORT
              value: {{ .Values.global.broker.port | quote }}
            - name: HORUSEC_PORT
              value: "8000"
            - name: HORUSEC_DATABASE_SQL_LOG_MODE
              value: "true"
            - name: HORUSEC_DATABASE_SQL_DIALECT
              value: postgres
            - name: HORUSEC_GRPC_AUTH_URL
              value: auth.horusec.svc.cluster.local:8007
            - name: HORUSEC_GRPC_USE_CERTS
              value: "false"
            - name: HORUSEC_GRPC_CERT_PATH
            - name: HORUSEC_DISABLED_BROKER
              value: {{ not .Values.global.broker.enabled | quote }}
            - name: HORUSEC_BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_DATABASE_SQL_URI
              valueFrom:
                secretKeyRef:
                  key: database-uri
                  name: database-uri
            - name: HORUSEC_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ .Values.global.jwt.secretName }}
          image: horuszup/horusec-api:v2.8.0
          imagePullPolicy: Always
          name: horusec-api
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: api
      serviceAccountName: api
      terminationGracePeriodSeconds: 30
