apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horusec-auth
  name: auth
  namespace: horusec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horusec-auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horusec-auth
    spec:
      containers:
        - env:
            - name: HORUSEC_SWAGGER_HOST
              value: 0.0.0.0
            - name: HORUSEC_PORT
              value: "8006"
            - name: HORUSEC_DATABASE_SQL_DIALECT
              value: {{ .Values.global.database.dialect }}
            - name: HORUSEC_DATABASE_SQL_LOG_MODE
              value: {{ .Values.global.database.logMode | quote }}
            - name: HORUSEC_API_URL
            - name: HORUSEC_GRPC_PORT
              value: "8007"
            - name: HORUSEC_GRPC_USE_CERTS
              value: "false"
            - name: HORUSEC_BROKER_HOST
              value: rabbitmq.queue
            - name: HORUSEC_BROKER_PORT
              value: {{ .Values.global.broker.port | quote }}
            - name: HORUSEC_DISABLED_BROKER
              value: {{ not .Values.global.broker.enabled | quote }}
            - name: HORUSEC_AUTH_TYPE
              value: horusec
            - name: HORUSEC_ENABLE_APPLICATION_ADMIN
              value: {{ .Values.global.enableAdmin | quote }}
            - name: HORUSEC_APPLICATION_ADMIN_DATA
              value: '{"username":"horusec-admin","email":"horusec-admin@example.com","password":"Devpass0*"}'
            - name: HORUSEC_BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_SQL_URI
              value: "postgresql://$(HORUSEC_DATABASE_USERNAME):$(HORUSEC_DATABASE_PASSWORD)@{{- .Values.global.database.host -}}:{{- .Values.global.database.port -}}/horusec_db{{- if not .Values.global.database.sslMode -}}?sslmode=disable{{- end -}}"
            - name: HORUSEC_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ .Values.global.jwt.secretName }}
          image: horuszup/horusec-auth:latest
          imagePullPolicy: Always
          name: horusec-auth
          ports:
          {{- range $key, $value := .Values.components.auth.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: auth
      serviceAccountName: auth
      terminationGracePeriodSeconds: 30
