apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horusec-manager
  name: manager
  namespace: horusec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horusec-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: horusec-manager
    spec:
      containers:
        - env:
            - name: REACT_APP_HORUSEC_ENDPOINT_API
              value: http:\/\/api-horus-dev.zup.com.br
            - name: REACT_APP_HORUSEC_ENDPOINT_ANALYTIC
              value: http:\/\/analytic-horus-dev.zup.com.br
            - name: REACT_APP_HORUSEC_ENDPOINT_ACCOUNT
              value: http:\/\/account-horus-dev.zup.com.br
            - name: REACT_APP_HORUSEC_ENDPOINT_AUTH
              value: http:\/\/auth-horus-dev.zup.com.br
          image: horuszup/horusec-manager:v1.7.1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: horusec-manager
          ports:
          {{- range $key, $value := .Values.components.manager.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: manager
      serviceAccountName: manager
      terminationGracePeriodSeconds: 30
