apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-account
  name: account
  namespace: horusec
spec:
  ports:
    - name: http
      port: 8003
      protocol: TCP
      targetPort: http
  selector:
    app: horusec-account
  type: ClusterIP
