{{- if .Values.components.analytic.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-analytic
  name: analytic
  namespace: horusec
spec:
  ports:
  {{- range $key, $value := .Values.components.analytic.port }}
    - name: {{ $key }}
      port: {{ $value }}
      protocol: TCP
      targetPort: {{ $key }}
  {{- end }}
  selector:
    app: horusec-analytic
  type: ClusterIP
{{- end }}