apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-analytic
  name: analytic
  namespace: horusec
spec:
  ports:
    - name: http
      port: 8005
      protocol: TCP
      targetPort: http
  selector:
    app: horusec-analytic
  type: ClusterIP
