apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-api
  name: api
  namespace: horusec
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app: horusec-api
  type: ClusterIP
