# permissions for end users to edit horusecauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horusecauth-editor-role
rules:
- apiGroups:
  - install.zup.com
  resources:
  - horusecauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.zup.com
  resources:
  - horusecauths/status
  verbs:
  - get
