# permissions for end users to view horusecapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horusecapi-viewer-role
rules:
- apiGroups:
  - install.zup.com
  resources:
  - horusecapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.zup.com
  resources:
  - horusecapis/status
  verbs:
  - get
