# permissions for end users to view horusecplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horusecplatform-viewer-role
rules:
- apiGroups:
  - install.horusec.io
  resources:
  - horusecplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.horusec.io
  resources:
  - horusecplatforms/status
  verbs:
  - get
