
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - install.horusec.io
  resources:
  - horusecplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.horusec.io
  resources:
  - horusecplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - install.horusec.io
  resources:
  - horusecplatforms/status
  verbs:
  - get
  - patch
  - update
