{{- if and .Values.components.api.enabled .Values.components.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: horusec-api
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.components.api.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: {{ .Values.components.api.port.http }}
            path: /
{{- end }}
