{{- if and .Values.components.manager.enabled .Values.components.manager.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: horusec-manager
  name: manager
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.components.manager.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: manager
              servicePort: {{ .Values.components.manager.port.http }}
            path: /
{{- end }}
