---
apiVersion: install.horusec.io/v2alpha1
kind: HorusecPlatform
metadata:
  name: horusecplatform-sample
spec:
  components:
    analytic:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
      database:
        host: horusdb.ce9hgcglmgxg.us-east-1.rds.amazonaws.com
        name: horusec_analytic_db
        password:
          secretKeyRef:
            key: database-password
            name: database-password
        user:
          secretKeyRef:
            key: database-username
            name: database-username
    api:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    auth:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    core:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    manager:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    messages:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    vulnerability:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
    webhook:
      container:
        image:
          registry: 671982376808.dkr.ecr.us-east-1.amazonaws.com
  global:
    database:
      host: horusdb.ce9hgcglmgxg.us-east-1.rds.amazonaws.com
      name: horusdb
      password:
        secretKeyRef:
          key: database-password
          name: database-password
      user:
        secretKeyRef:
          key: database-username
          name: database-username
