---
apiVersion: install.horusec.io/v2alpha1
kind: HorusecPlatform
metadata:
  name: horusecplatform-sample
spec:
  components:
    analytic:
      database:
        host: horusdb.ce9hgcglmgxg.us-east-1.rds.amazonaws.com
        name: horusec_analytic_db
        password:
          secretKeyRef:
            key: password
            name: horusec-database
        user:
          secretKeyRef:
            key: username
            name: horusec-database
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    api:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    auth:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    core:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    manager:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    messages:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    vulnerability:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    webhook:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
  global:
    broker:
      host: rabbitmq
      password:
        secretKeyRef:
          key: password
          name: horusec-broker
      user:
        secretKeyRef:
          key: username
          name: horusec-broker
    database:
      host: horusdb.ce9hgcglmgxg.us-east-1.rds.amazonaws.com
      name: horusdb
      password:
        secretKeyRef:
          key: password
          name: horusec-database
      user:
        secretKeyRef:
          key: username
          name: horusec-database
