{{- if .Release.IsInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: migration
    spec:
      restartPolicy: Never
      containers:
        - name: horusec-database-migration
          image: "horuszup/horusec-migration:latest"
          command: [ "migrate.sh" ]
          env:
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_SQL_URI
              value: "postgresql://$(HORUSEC_DATABASE_USERNAME):$(HORUSEC_DATABASE_PASSWORD)@{{- .Values.global.database.host -}}:{{- .Values.global.database.port -}}/horusec_db{{- if not .Values.global.database.sslMode -}}?sslmode=disable{{- end -}}"
{{- end }}